### ISSUE TITLE
Petra A-1 - Punchout Required

### ISSUE THREAD

**Issue by commercebuild** [commercebuild/cfw-issues#4]
See PetrA-1 uses punchout: https://commercebuild.slack.com/archives/C04QKU4AW3Z/p1719605996371749?thread_ts=1717519446.060349&cid=C04QKU4AW3Z

Should be its own plugin

**Comment by donavon-commercebuild** [comment]
TradeCentric: https://tradecentric.com/punchout/woocommerce/
Greenwing: https://www.greenwingtechnology.com/woocommerce-punchout-connector/
